project:
  type: website
  output-dir: docs

render: 
  - index.qmd

website:
  favicon: "images/logo_fau_red.svg"
  page-navigation: true
  title: "Digital behavioral data"
  description: "Homepage for Digital behavior data at Friedrich-Alexander-Universtität Erlangen-Nürnberg, Winter semester 2022/23."
 
  repo-url: https://github.com/chrdrn/digital-behavioral-data
  repo-actions: [edit, issue]

  reader-mode: true
  
  page-footer: 
   left: "Copyright 2022, Christoph Adrian"
   right: "This page is built with [Quarto](https://quarto.org/)."
  
  sidebar:
    logo: "images/dbd_hex.png"
    tools: 
    - icon: globe
      href: https://www.kommunikationswissenschaft.rw.fau.de/lehre/master/digital-behavioral-data/
    - icon: twitter
      href: https://twitter.com/chrdrn
    - icon: github
      href: https://github.com/chrdrn/digital-behavioral-data
    - icon: code-square
      href: https://github.com/chrdrn/dbd_binder
      text: Gitlab Repository for Showcases
    - icon: box-arrow-up-right
      href: https://mybinder.org/v2/gh/chrdrn/dbd_binder/HEAD
      text: Start Binder
    
    style: floating
    search: true
    collapse-level: 1
    contents: 
      - section: "Kick-Off"
        contents:
          - "content/01-kick-off/01-slides.qmd"
      - section: "Introduction"
        contents:
          - "content/02-dbb-introduction_overview/02-slides.qmd"
      - section: "Data Collection"
        contents:
          - "content/03-dbd-data_collection/03-slides.qmd"
      - section: "API Access: Twitter"
        contents:
          - "content/04-api_access-twitter/04-slides.qmd"
          - "content/04-api_access-twitter/04-exercise.qmd"
      - section: "API Access: YouTube"
        contents:
          - "content/05-api_access-youtube/05-slides.qmd"
          - "content/05-api_access-youtube/05-exercise.qmd"
      - section: "API Access: Reddit"
        contents:
          - "content/06-api_access-reddit/06-slides.qmd"
          - "content/06-api_access-reddit/06-exercise.qmd"
      - section: "Webscraping: TikTok"
        contents:
          - "content/07-webscraping-tiktok/07-slides.qmd"
          - "content/07-webscraping-tiktok/07-exercise.qmd"



format:
  html:
    theme:
      light: [journal, theme.scss]
      dark: [journal, theme-dark.scss]
    css: styles.css
    toc: true
